// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cdf_cpp
double cdf_cpp(double x, NumericVector par);
RcppExport SEXP _CpmLogLogisticPMITICS_cdf_cpp(SEXP xSEXP, SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(cdf_cpp(x, par));
    return rcpp_result_gen;
END_RCPP
}
// pdf_cpp
double pdf_cpp(double x, NumericVector par);
RcppExport SEXP _CpmLogLogisticPMITICS_pdf_cpp(SEXP xSEXP, SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(pdf_cpp(x, par));
    return rcpp_result_gen;
END_RCPP
}
// sur_cpp
double sur_cpp(double x, NumericVector par);
RcppExport SEXP _CpmLogLogisticPMITICS_sur_cpp(SEXP xSEXP, SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(sur_cpp(x, par));
    return rcpp_result_gen;
END_RCPP
}
// qnt_cpp
double qnt_cpp(double x, NumericVector par);
RcppExport SEXP _CpmLogLogisticPMITICS_qnt_cpp(SEXP xSEXP, SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(qnt_cpp(x, par));
    return rcpp_result_gen;
END_RCPP
}
// moments_cpp
List moments_cpp(NumericVector par);
RcppExport SEXP _CpmLogLogisticPMITICS_moments_cpp(SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(moments_cpp(par));
    return rcpp_result_gen;
END_RCPP
}
// Cpm_star_fun_cpp
double Cpm_star_fun_cpp(NumericVector par, NumericVector Cpm_par);
RcppExport SEXP _CpmLogLogisticPMITICS_Cpm_star_fun_cpp(SEXP parSEXP, SEXP Cpm_parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Cpm_par(Cpm_parSEXP);
    rcpp_result_gen = Rcpp::wrap(Cpm_star_fun_cpp(par, Cpm_par));
    return rcpp_result_gen;
END_RCPP
}
// Cpm_star_grad_cpp
NumericVector Cpm_star_grad_cpp(NumericVector par, NumericVector Cpm_par, double eps);
RcppExport SEXP _CpmLogLogisticPMITICS_Cpm_star_grad_cpp(SEXP parSEXP, SEXP Cpm_parSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Cpm_par(Cpm_parSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(Cpm_star_grad_cpp(par, Cpm_par, eps));
    return rcpp_result_gen;
END_RCPP
}
// Cpm_star_hessian_cpp
NumericMatrix Cpm_star_hessian_cpp(NumericVector par, NumericVector Cpm_par, double eps);
RcppExport SEXP _CpmLogLogisticPMITICS_Cpm_star_hessian_cpp(SEXP parSEXP, SEXP Cpm_parSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Cpm_par(Cpm_parSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(Cpm_star_hessian_cpp(par, Cpm_par, eps));
    return rcpp_result_gen;
END_RCPP
}
// simulate_PMITICS_cpp
List simulate_PMITICS_cpp(NumericVector par, int n, int m, double censor_prop, double l_prop, NumericVector Rprog);
RcppExport SEXP _CpmLogLogisticPMITICS_simulate_PMITICS_cpp(SEXP parSEXP, SEXP nSEXP, SEXP mSEXP, SEXP censor_propSEXP, SEXP l_propSEXP, SEXP RprogSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type censor_prop(censor_propSEXP);
    Rcpp::traits::input_parameter< double >::type l_prop(l_propSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rprog(RprogSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_PMITICS_cpp(par, n, m, censor_prop, l_prop, Rprog));
    return rcpp_result_gen;
END_RCPP
}
// loglik_cpp
double loglik_cpp(NumericVector par, NumericVector X, NumericVector L, NumericVector R, NumericVector T, NumericVector Rprog, int final_right_censored);
RcppExport SEXP _CpmLogLogisticPMITICS_loglik_cpp(SEXP parSEXP, SEXP XSEXP, SEXP LSEXP, SEXP RSEXP, SEXP TSEXP, SEXP RprogSEXP, SEXP final_right_censoredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type L(LSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type R(RSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rprog(RprogSEXP);
    Rcpp::traits::input_parameter< int >::type final_right_censored(final_right_censoredSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_cpp(par, X, L, R, T, Rprog, final_right_censored));
    return rcpp_result_gen;
END_RCPP
}
// lik_cpp
double lik_cpp(NumericVector par, NumericVector X, NumericVector L, NumericVector R, NumericVector T, NumericVector Rprog, int final_right_censored);
RcppExport SEXP _CpmLogLogisticPMITICS_lik_cpp(SEXP parSEXP, SEXP XSEXP, SEXP LSEXP, SEXP RSEXP, SEXP TSEXP, SEXP RprogSEXP, SEXP final_right_censoredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type L(LSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type R(RSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rprog(RprogSEXP);
    Rcpp::traits::input_parameter< int >::type final_right_censored(final_right_censoredSEXP);
    rcpp_result_gen = Rcpp::wrap(lik_cpp(par, X, L, R, T, Rprog, final_right_censored));
    return rcpp_result_gen;
END_RCPP
}
// logmps_cpp
double logmps_cpp(NumericVector par, NumericVector X, NumericVector L, NumericVector R, NumericVector T, NumericVector Rprog, int final_right_censored);
RcppExport SEXP _CpmLogLogisticPMITICS_logmps_cpp(SEXP parSEXP, SEXP XSEXP, SEXP LSEXP, SEXP RSEXP, SEXP TSEXP, SEXP RprogSEXP, SEXP final_right_censoredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type L(LSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type R(RSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rprog(RprogSEXP);
    Rcpp::traits::input_parameter< int >::type final_right_censored(final_right_censoredSEXP);
    rcpp_result_gen = Rcpp::wrap(logmps_cpp(par, X, L, R, T, Rprog, final_right_censored));
    return rcpp_result_gen;
END_RCPP
}
// mps_cpp
double mps_cpp(NumericVector par, NumericVector X, NumericVector L, NumericVector R, NumericVector T, NumericVector Rprog, int final_right_censored);
RcppExport SEXP _CpmLogLogisticPMITICS_mps_cpp(SEXP parSEXP, SEXP XSEXP, SEXP LSEXP, SEXP RSEXP, SEXP TSEXP, SEXP RprogSEXP, SEXP final_right_censoredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type L(LSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type R(RSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rprog(RprogSEXP);
    Rcpp::traits::input_parameter< int >::type final_right_censored(final_right_censoredSEXP);
    rcpp_result_gen = Rcpp::wrap(mps_cpp(par, X, L, R, T, Rprog, final_right_censored));
    return rcpp_result_gen;
END_RCPP
}
// Estim_profile_cpp
Rcpp::List Estim_profile_cpp(arma::vec par, arma::vec par_init, arma::vec X, arma::vec L, arma::vec R, arma::vec T, arma::vec Rprog, int final_right_censored, arma::vec Cpm_par, arma::vec lower_lim, arma::vec upper_lim, std::string type);
RcppExport SEXP _CpmLogLogisticPMITICS_Estim_profile_cpp(SEXP parSEXP, SEXP par_initSEXP, SEXP XSEXP, SEXP LSEXP, SEXP RSEXP, SEXP TSEXP, SEXP RprogSEXP, SEXP final_right_censoredSEXP, SEXP Cpm_parSEXP, SEXP lower_limSEXP, SEXP upper_limSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par_init(par_initSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type T(TSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Rprog(RprogSEXP);
    Rcpp::traits::input_parameter< int >::type final_right_censored(final_right_censoredSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Cpm_par(Cpm_parSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lower_lim(lower_limSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type upper_lim(upper_limSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(Estim_profile_cpp(par, par_init, X, L, R, T, Rprog, final_right_censored, Cpm_par, lower_lim, upper_lim, type));
    return rcpp_result_gen;
END_RCPP
}
// make_boot_p_cpp
Rcpp::NumericVector make_boot_p_cpp(arma::vec x, double true_val, double alpha);
RcppExport SEXP _CpmLogLogisticPMITICS_make_boot_p_cpp(SEXP xSEXP, SEXP true_valSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type true_val(true_valSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(make_boot_p_cpp(x, true_val, alpha));
    return rcpp_result_gen;
END_RCPP
}
// make_boot_t_cpp
Rcpp::NumericVector make_boot_t_cpp(arma::vec tstar, double est, double se0, double true_val, double alpha);
RcppExport SEXP _CpmLogLogisticPMITICS_make_boot_t_cpp(SEXP tstarSEXP, SEXP estSEXP, SEXP se0SEXP, SEXP true_valSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type tstar(tstarSEXP);
    Rcpp::traits::input_parameter< double >::type est(estSEXP);
    Rcpp::traits::input_parameter< double >::type se0(se0SEXP);
    Rcpp::traits::input_parameter< double >::type true_val(true_valSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(make_boot_t_cpp(tstar, est, se0, true_val, alpha));
    return rcpp_result_gen;
END_RCPP
}
// make_boot_t_log_cpp
Rcpp::NumericVector make_boot_t_log_cpp(arma::vec tlog, double est, double se0, double true_val, double alpha);
RcppExport SEXP _CpmLogLogisticPMITICS_make_boot_t_log_cpp(SEXP tlogSEXP, SEXP estSEXP, SEXP se0SEXP, SEXP true_valSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type tlog(tlogSEXP);
    Rcpp::traits::input_parameter< double >::type est(estSEXP);
    Rcpp::traits::input_parameter< double >::type se0(se0SEXP);
    Rcpp::traits::input_parameter< double >::type true_val(true_valSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(make_boot_t_log_cpp(tlog, est, se0, true_val, alpha));
    return rcpp_result_gen;
END_RCPP
}
// Boot_fun_cpp
Rcpp::List Boot_fun_cpp(arma::vec par, arma::vec init, arma::vec se, int n, int m, double censor_prop, double l_prop, arma::vec Rprog, arma::vec lower, arma::vec upper, arma::vec Cpm_par, int BOOT, double alpha, std::string type);
RcppExport SEXP _CpmLogLogisticPMITICS_Boot_fun_cpp(SEXP parSEXP, SEXP initSEXP, SEXP seSEXP, SEXP nSEXP, SEXP mSEXP, SEXP censor_propSEXP, SEXP l_propSEXP, SEXP RprogSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP Cpm_parSEXP, SEXP BOOTSEXP, SEXP alphaSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type init(initSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type se(seSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type censor_prop(censor_propSEXP);
    Rcpp::traits::input_parameter< double >::type l_prop(l_propSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Rprog(RprogSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Cpm_par(Cpm_parSEXP);
    Rcpp::traits::input_parameter< int >::type BOOT(BOOTSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(Boot_fun_cpp(par, init, se, n, m, censor_prop, l_prop, Rprog, lower, upper, Cpm_par, BOOT, alpha, type));
    return rcpp_result_gen;
END_RCPP
}
// MH_sample_cpp
Rcpp::List MH_sample_cpp(NumericVector par, std::string type, NumericVector init, NumericVector X, NumericVector L, NumericVector R, NumericVector T, NumericVector Rprog, int final_right_censored, NumericVector se, NumericVector h, NumericVector Cpm_par, int MC_size, NumericVector lower, NumericVector upper);
RcppExport SEXP _CpmLogLogisticPMITICS_MH_sample_cpp(SEXP parSEXP, SEXP typeSEXP, SEXP initSEXP, SEXP XSEXP, SEXP LSEXP, SEXP RSEXP, SEXP TSEXP, SEXP RprogSEXP, SEXP final_right_censoredSEXP, SEXP seSEXP, SEXP hSEXP, SEXP Cpm_parSEXP, SEXP MC_sizeSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type init(initSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type L(LSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type R(RSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rprog(RprogSEXP);
    Rcpp::traits::input_parameter< int >::type final_right_censored(final_right_censoredSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type se(seSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Cpm_par(Cpm_parSEXP);
    Rcpp::traits::input_parameter< int >::type MC_size(MC_sizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(MH_sample_cpp(par, type, init, X, L, R, T, Rprog, final_right_censored, se, h, Cpm_par, MC_size, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// MCMC_cpp
Rcpp::List MCMC_cpp(NumericVector par, std::string type, NumericVector init, NumericVector X, NumericVector L, NumericVector R, NumericVector T, NumericVector Rprog, int final_right_censored, NumericVector se, NumericVector h, NumericVector Cpm_par, int MC_size, int MC_burn, NumericVector c, NumericVector lower, NumericVector upper);
RcppExport SEXP _CpmLogLogisticPMITICS_MCMC_cpp(SEXP parSEXP, SEXP typeSEXP, SEXP initSEXP, SEXP XSEXP, SEXP LSEXP, SEXP RSEXP, SEXP TSEXP, SEXP RprogSEXP, SEXP final_right_censoredSEXP, SEXP seSEXP, SEXP hSEXP, SEXP Cpm_parSEXP, SEXP MC_sizeSEXP, SEXP MC_burnSEXP, SEXP cSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type init(initSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type L(LSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type R(RSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rprog(RprogSEXP);
    Rcpp::traits::input_parameter< int >::type final_right_censored(final_right_censoredSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type se(seSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Cpm_par(Cpm_parSEXP);
    Rcpp::traits::input_parameter< int >::type MC_size(MC_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type MC_burn(MC_burnSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(MCMC_cpp(par, type, init, X, L, R, T, Rprog, final_right_censored, se, h, Cpm_par, MC_size, MC_burn, c, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// HyperPara_PMITICS_cpp
Rcpp::NumericVector HyperPara_PMITICS_cpp(Rcpp::NumericVector para, int n, int m, double censor_prop, double l_prop, Rcpp::NumericVector Rprog, Rcpp::NumericVector lower, Rcpp::NumericVector upper, int Hyper_It, std::string method);
RcppExport SEXP _CpmLogLogisticPMITICS_HyperPara_PMITICS_cpp(SEXP paraSEXP, SEXP nSEXP, SEXP mSEXP, SEXP censor_propSEXP, SEXP l_propSEXP, SEXP RprogSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP Hyper_ItSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type para(paraSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type censor_prop(censor_propSEXP);
    Rcpp::traits::input_parameter< double >::type l_prop(l_propSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Rprog(RprogSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type Hyper_It(Hyper_ItSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(HyperPara_PMITICS_cpp(para, n, m, censor_prop, l_prop, Rprog, lower, upper, Hyper_It, method));
    return rcpp_result_gen;
END_RCPP
}
// TK_GEL_cpp
Rcpp::List TK_GEL_cpp(arma::vec True_para, arma::vec Init_para, int n, arma::vec X, arma::vec L, arma::vec R, arma::vec T, arma::vec Rprog, int final_right_censored, arma::vec Cpm_par, arma::vec h, double q, std::string type);
RcppExport SEXP _CpmLogLogisticPMITICS_TK_GEL_cpp(SEXP True_paraSEXP, SEXP Init_paraSEXP, SEXP nSEXP, SEXP XSEXP, SEXP LSEXP, SEXP RSEXP, SEXP TSEXP, SEXP RprogSEXP, SEXP final_right_censoredSEXP, SEXP Cpm_parSEXP, SEXP hSEXP, SEXP qSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type True_para(True_paraSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Init_para(Init_paraSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type T(TSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Rprog(RprogSEXP);
    Rcpp::traits::input_parameter< int >::type final_right_censored(final_right_censoredSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Cpm_par(Cpm_parSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(TK_GEL_cpp(True_para, Init_para, n, X, L, R, T, Rprog, final_right_censored, Cpm_par, h, q, type));
    return rcpp_result_gen;
END_RCPP
}
// TK_LINEX_cpp
Rcpp::List TK_LINEX_cpp(arma::vec True_para, arma::vec Init_para, int n, arma::vec X, arma::vec L, arma::vec R, arma::vec T, arma::vec Rprog, int final_right_censored, arma::vec Cpm_par, arma::vec h, double c, std::string type);
RcppExport SEXP _CpmLogLogisticPMITICS_TK_LINEX_cpp(SEXP True_paraSEXP, SEXP Init_paraSEXP, SEXP nSEXP, SEXP XSEXP, SEXP LSEXP, SEXP RSEXP, SEXP TSEXP, SEXP RprogSEXP, SEXP final_right_censoredSEXP, SEXP Cpm_parSEXP, SEXP hSEXP, SEXP cSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type True_para(True_paraSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Init_para(Init_paraSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type T(TSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Rprog(RprogSEXP);
    Rcpp::traits::input_parameter< int >::type final_right_censored(final_right_censoredSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Cpm_par(Cpm_parSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(TK_LINEX_cpp(True_para, Init_para, n, X, L, R, T, Rprog, final_right_censored, Cpm_par, h, c, type));
    return rcpp_result_gen;
END_RCPP
}
// Lindley_GEL_cpp
Rcpp::List Lindley_GEL_cpp(arma::vec True_para, arma::vec Init_para, int n, arma::vec X, arma::vec L, arma::vec R, arma::vec T, arma::vec Rprog, int final_right_censored, arma::vec Cpm_par, arma::vec h, double q, std::string type);
RcppExport SEXP _CpmLogLogisticPMITICS_Lindley_GEL_cpp(SEXP True_paraSEXP, SEXP Init_paraSEXP, SEXP nSEXP, SEXP XSEXP, SEXP LSEXP, SEXP RSEXP, SEXP TSEXP, SEXP RprogSEXP, SEXP final_right_censoredSEXP, SEXP Cpm_parSEXP, SEXP hSEXP, SEXP qSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type True_para(True_paraSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Init_para(Init_paraSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type T(TSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Rprog(RprogSEXP);
    Rcpp::traits::input_parameter< int >::type final_right_censored(final_right_censoredSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Cpm_par(Cpm_parSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(Lindley_GEL_cpp(True_para, Init_para, n, X, L, R, T, Rprog, final_right_censored, Cpm_par, h, q, type));
    return rcpp_result_gen;
END_RCPP
}
// Lindley_LINEX_cpp
Rcpp::List Lindley_LINEX_cpp(arma::vec True_para, arma::vec Init_para, int n, arma::vec X, arma::vec L, arma::vec R, arma::vec T, arma::vec Rprog, int final_right_censored, arma::vec Cpm_par, arma::vec h, double c, std::string type);
RcppExport SEXP _CpmLogLogisticPMITICS_Lindley_LINEX_cpp(SEXP True_paraSEXP, SEXP Init_paraSEXP, SEXP nSEXP, SEXP XSEXP, SEXP LSEXP, SEXP RSEXP, SEXP TSEXP, SEXP RprogSEXP, SEXP final_right_censoredSEXP, SEXP Cpm_parSEXP, SEXP hSEXP, SEXP cSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type True_para(True_paraSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Init_para(Init_paraSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type T(TSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Rprog(RprogSEXP);
    Rcpp::traits::input_parameter< int >::type final_right_censored(final_right_censoredSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Cpm_par(Cpm_parSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(Lindley_LINEX_cpp(True_para, Init_para, n, X, L, R, T, Rprog, final_right_censored, Cpm_par, h, c, type));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CpmLogLogisticPMITICS_cdf_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_cdf_cpp, 2},
    {"_CpmLogLogisticPMITICS_pdf_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_pdf_cpp, 2},
    {"_CpmLogLogisticPMITICS_sur_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_sur_cpp, 2},
    {"_CpmLogLogisticPMITICS_qnt_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_qnt_cpp, 2},
    {"_CpmLogLogisticPMITICS_moments_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_moments_cpp, 1},
    {"_CpmLogLogisticPMITICS_Cpm_star_fun_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_Cpm_star_fun_cpp, 2},
    {"_CpmLogLogisticPMITICS_Cpm_star_grad_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_Cpm_star_grad_cpp, 3},
    {"_CpmLogLogisticPMITICS_Cpm_star_hessian_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_Cpm_star_hessian_cpp, 3},
    {"_CpmLogLogisticPMITICS_simulate_PMITICS_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_simulate_PMITICS_cpp, 6},
    {"_CpmLogLogisticPMITICS_loglik_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_loglik_cpp, 7},
    {"_CpmLogLogisticPMITICS_lik_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_lik_cpp, 7},
    {"_CpmLogLogisticPMITICS_logmps_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_logmps_cpp, 7},
    {"_CpmLogLogisticPMITICS_mps_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_mps_cpp, 7},
    {"_CpmLogLogisticPMITICS_Estim_profile_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_Estim_profile_cpp, 12},
    {"_CpmLogLogisticPMITICS_make_boot_p_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_make_boot_p_cpp, 3},
    {"_CpmLogLogisticPMITICS_make_boot_t_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_make_boot_t_cpp, 5},
    {"_CpmLogLogisticPMITICS_make_boot_t_log_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_make_boot_t_log_cpp, 5},
    {"_CpmLogLogisticPMITICS_Boot_fun_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_Boot_fun_cpp, 14},
    {"_CpmLogLogisticPMITICS_MH_sample_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_MH_sample_cpp, 15},
    {"_CpmLogLogisticPMITICS_MCMC_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_MCMC_cpp, 17},
    {"_CpmLogLogisticPMITICS_HyperPara_PMITICS_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_HyperPara_PMITICS_cpp, 10},
    {"_CpmLogLogisticPMITICS_TK_GEL_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_TK_GEL_cpp, 13},
    {"_CpmLogLogisticPMITICS_TK_LINEX_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_TK_LINEX_cpp, 13},
    {"_CpmLogLogisticPMITICS_Lindley_GEL_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_Lindley_GEL_cpp, 13},
    {"_CpmLogLogisticPMITICS_Lindley_LINEX_cpp", (DL_FUNC) &_CpmLogLogisticPMITICS_Lindley_LINEX_cpp, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_CpmLogLogisticPMITICS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
