# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cdf_cpp <- function(x, par) {
    .Call(`_CpmLogLogisticPMITICS_cdf_cpp`, x, par)
}

pdf_cpp <- function(x, par) {
    .Call(`_CpmLogLogisticPMITICS_pdf_cpp`, x, par)
}

sur_cpp <- function(x, par) {
    .Call(`_CpmLogLogisticPMITICS_sur_cpp`, x, par)
}

qnt_cpp <- function(x, par) {
    .Call(`_CpmLogLogisticPMITICS_qnt_cpp`, x, par)
}

moments_cpp <- function(par) {
    .Call(`_CpmLogLogisticPMITICS_moments_cpp`, par)
}

Cpm_star_fun_cpp <- function(par, Cpm_par) {
    .Call(`_CpmLogLogisticPMITICS_Cpm_star_fun_cpp`, par, Cpm_par)
}

Cpm_star_grad_cpp <- function(par, Cpm_par, eps = 1e-6) {
    .Call(`_CpmLogLogisticPMITICS_Cpm_star_grad_cpp`, par, Cpm_par, eps)
}

Cpm_star_hessian_cpp <- function(par, Cpm_par, eps = 1e-5) {
    .Call(`_CpmLogLogisticPMITICS_Cpm_star_hessian_cpp`, par, Cpm_par, eps)
}

simulate_PMITICS_cpp <- function(par, n, m, censor_prop, l_prop, Rprog) {
    .Call(`_CpmLogLogisticPMITICS_simulate_PMITICS_cpp`, par, n, m, censor_prop, l_prop, Rprog)
}

loglik_cpp <- function(par, X, L, R, T, Rprog, final_right_censored = 0L) {
    .Call(`_CpmLogLogisticPMITICS_loglik_cpp`, par, X, L, R, T, Rprog, final_right_censored)
}

lik_cpp <- function(par, X, L, R, T, Rprog, final_right_censored = 0L) {
    .Call(`_CpmLogLogisticPMITICS_lik_cpp`, par, X, L, R, T, Rprog, final_right_censored)
}

logmps_cpp <- function(par, X, L, R, T, Rprog, final_right_censored = 0L) {
    .Call(`_CpmLogLogisticPMITICS_logmps_cpp`, par, X, L, R, T, Rprog, final_right_censored)
}

mps_cpp <- function(par, X, L, R, T, Rprog, final_right_censored = 0L) {
    .Call(`_CpmLogLogisticPMITICS_mps_cpp`, par, X, L, R, T, Rprog, final_right_censored)
}

Estim_profile_cpp <- function(par, par_init, X, L, R, T, Rprog, final_right_censored, Cpm_par, lower_lim, upper_lim, type = "LK") {
    .Call(`_CpmLogLogisticPMITICS_Estim_profile_cpp`, par, par_init, X, L, R, T, Rprog, final_right_censored, Cpm_par, lower_lim, upper_lim, type)
}

make_boot_p_cpp <- function(x, true_val, alpha) {
    .Call(`_CpmLogLogisticPMITICS_make_boot_p_cpp`, x, true_val, alpha)
}

make_boot_t_cpp <- function(tstar, est, se0, true_val, alpha) {
    .Call(`_CpmLogLogisticPMITICS_make_boot_t_cpp`, tstar, est, se0, true_val, alpha)
}

make_boot_t_log_cpp <- function(tlog, est, se0, true_val, alpha) {
    .Call(`_CpmLogLogisticPMITICS_make_boot_t_log_cpp`, tlog, est, se0, true_val, alpha)
}

Boot_fun_cpp <- function(par, init, se, n, m, censor_prop, l_prop, Rprog, lower, upper, Cpm_par, BOOT = 1000L, alpha = 0.05, type = "LK") {
    .Call(`_CpmLogLogisticPMITICS_Boot_fun_cpp`, par, init, se, n, m, censor_prop, l_prop, Rprog, lower, upper, Cpm_par, BOOT, alpha, type)
}

MH_sample_cpp <- function(par, type, init, X, L, R, T, Rprog, final_right_censored, se, h, Cpm_par, MC_size, lower, upper) {
    .Call(`_CpmLogLogisticPMITICS_MH_sample_cpp`, par, type, init, X, L, R, T, Rprog, final_right_censored, se, h, Cpm_par, MC_size, lower, upper)
}

MCMC_cpp <- function(par, type, init, X, L, R, T, Rprog, final_right_censored, se, h, Cpm_par, MC_size, MC_burn, c, lower, upper) {
    .Call(`_CpmLogLogisticPMITICS_MCMC_cpp`, par, type, init, X, L, R, T, Rprog, final_right_censored, se, h, Cpm_par, MC_size, MC_burn, c, lower, upper)
}

HyperPara_PMITICS_cpp <- function(para, n, m, censor_prop, l_prop, Rprog, lower, upper, Hyper_It = 100L, method = "Nelder-Mead") {
    .Call(`_CpmLogLogisticPMITICS_HyperPara_PMITICS_cpp`, para, n, m, censor_prop, l_prop, Rprog, lower, upper, Hyper_It, method)
}

TK_GEL_cpp <- function(True_para, Init_para, n, X, L, R, T, Rprog, final_right_censored, Cpm_par, h, q, type) {
    .Call(`_CpmLogLogisticPMITICS_TK_GEL_cpp`, True_para, Init_para, n, X, L, R, T, Rprog, final_right_censored, Cpm_par, h, q, type)
}

TK_LINEX_cpp <- function(True_para, Init_para, n, X, L, R, T, Rprog, final_right_censored, Cpm_par, h, c, type) {
    .Call(`_CpmLogLogisticPMITICS_TK_LINEX_cpp`, True_para, Init_para, n, X, L, R, T, Rprog, final_right_censored, Cpm_par, h, c, type)
}

Lindley_GEL_cpp <- function(True_para, Init_para, n, X, L, R, T, Rprog, final_right_censored, Cpm_par, h, q, type) {
    .Call(`_CpmLogLogisticPMITICS_Lindley_GEL_cpp`, True_para, Init_para, n, X, L, R, T, Rprog, final_right_censored, Cpm_par, h, q, type)
}

Lindley_LINEX_cpp <- function(True_para, Init_para, n, X, L, R, T, Rprog, final_right_censored, Cpm_par, h, c, type) {
    .Call(`_CpmLogLogisticPMITICS_Lindley_LINEX_cpp`, True_para, Init_para, n, X, L, R, T, Rprog, final_right_censored, Cpm_par, h, c, type)
}

